**Exercise 5.1** Write a version of `correlate` that returns the same result as `np.correlate` with `mode="same"`. Hint: use the NumPy function `pad`.

In [2]:
%matplotlib inline

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import seaborn as sns


The `kth` element of the cross-correlation of an array `a`, with window `w`, gives a new array `c` is computed using:

In [3]:
def c_k(a, w, k):
    N = len(w)
    return sum(a[k:k+N]*w)

The original `correlate` function which computes the elements of `c` for all `k` is

In [4]:
def correlate(row, window):
    cols = len(row)
    N = len(window)
    c = [c_k(row, window, k) for k in range(cols-N+1)]
    return np.array(c)

To modify this function so that the output is the same as that of `np.correlate` with `mode="same"`, we can use the `np.pad` function:

In [11]:
N = 10
row = np.arange(N)
window = [1, 1, 1]
np.pad(row, 1, 'constant')

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [30]:
def correlate_mod(row, window):
    cols = len(row)
    N = len(window)
    c = [c_k(np.pad(row, 1, 'constant'), window, k) for k in range(cols)]
    return np.array(c)

In [31]:
c1 = np.correlate(row, window, 'same')
c2 = correlate_mod(row, window)
print (c1)
print (c2)

[ 1  3  6  9 12 15 18 21 24 17]
[ 1  3  6  9 12 15 18 21 24 17]
